# Generated by Django 2.0.5 on 2019-04-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
